const { withDangerousMod } = require('@expo/config-plugins');
const { mergeContents } = require('@expo/config-plugins/build/utils/generateCode');
const fs = require('fs');
const path = require('path');

// React Native 0.79 bundles fmt 11.0.2, whose consteval format-string checking
// fails to compile under the Clang shipped with Xcode 26 (the "latest" EAS
// image we build the store profiles against):
//
//   call to consteval function 'fmt::basic_format_string<...>' is not a
//   constant expression
//
// fmt headers are pulled in transitively by RCT-Folly, glog and React-logger,
// so the error surfaces across several Pod targets. Defining FMT_USE_CONSTEVAL=0
// makes fmt fall back to runtime format-string checks and sidesteps the broken
// consteval evaluation. Applied to every Pod target via the Podfile post_install
// because ios/ is regenerated by prebuild and can't be hand-edited.
const FMT_FIX = `
    # [withFmtConstevalFix] Disable fmt consteval format-string checks so the
    # RN-bundled fmt 11.0.2 compiles under Xcode 26's Clang.
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build_config|
        defs = build_config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] || ['$(inherited)']
        defs = [defs] unless defs.is_a?(Array)
        defs << 'FMT_USE_CONSTEVAL=0' unless defs.include?('FMT_USE_CONSTEVAL=0')
        build_config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = defs
      end
    end`;

/**
 * Expo config plugin: patch the iOS Podfile post_install to disable fmt's
 * consteval format-string checking (Xcode 26 / fmt 11.0.2 incompatibility).
 */
function withFmtConstevalFix(config) {
  return withDangerousMod(config, [
    'ios',
    async (config) => {
      const podfilePath = path.join(
        config.modRequest.platformProjectRoot,
        'Podfile'
      );
      const contents = fs.readFileSync(podfilePath, 'utf8');

      const merged = mergeContents({
        tag: 'withFmtConstevalFix',
        src: contents,
        newSrc: FMT_FIX,
        anchor: /post_install do \|installer\|/,
        offset: 1,
        comment: '#',
      });

      if (merged.didMerge) {
        fs.writeFileSync(podfilePath, merged.contents);
      }

      return config;
    },
  ]);
}

module.exports = withFmtConstevalFix;
